"""Reviewed-shape, draft learning copy for the category catalogue.

This file is deliberately separate from the crossword generator. It is the
human-editable source for category introductions, completion passages, hero-word
ordering, and bilingual lesson sentences. The copy is suitable for a prototype,
but every entry remains ``draft`` until a Bangladeshi Bengali language reviewer
and a primary-school educator approve it.
"""

CATALOG_VERSION = "2026.09.02-3"
CONTENT_REVIEW_NOTICE = (
    "Draft learning copy: Bengali language, cultural fit, and age suitability "
    "must be approved by a Bangladeshi Bengali reviewer and primary educator "
    "before release."
)


CATEGORY_CONTENT = {
    "animals": {
        "introductionEn": "Animals live with us on farms, in homes, and in the wild.",
        "introductionBn": "প্রাণী আমাদের সঙ্গে খামারে, বাড়িতে ও বনে বাস করে।",
        "completionEn": "A cat and a dog may live near our home. A cow, hen, and goat are familiar farm animals in Bangladesh.",
        "completionBn": "বিড়াল ও কুকুর আমাদের বাড়ির কাছে থাকতে পারে। গরু, মুরগি ও ছাগল বাংলাদেশের পরিচিত খামারের প্রাণী।",
        "completionWords": ["CAT", "DOG", "COW", "HEN", "GOAT"],
        "lessons": {
            "cat": ("The cat sleeps beside our door.", "বিড়ালটি আমাদের দরজার পাশে ঘুমায়।"),
            "cow": ("The cow eats green grass.", "গরুটি সবুজ ঘাস খায়।"),
            "dog": ("The dog guards our home.", "কুকুরটি আমাদের বাড়ি পাহারা দেয়।"),
            "hen": ("The hen walks around the yard.", "মুরগিটি উঠানে হাঁটে।"),
            "rat": ("The rat hides behind the rice sack.", "ইঁদুরটি চালের বস্তার পেছনে লুকায়।"),
            "ant": ("An ant carries a tiny grain of rice.", "একটি পিঁপড়া চালের ছোট দানা বয়ে নিয়ে যায়।"),
            "bee": ("A bee visits the mustard flower.", "একটি মৌমাছি সরিষার ফুলে বসে।"),
            "bear": ("The bear walks through the forest.", "ভালুকটি বনের ভেতর দিয়ে হাঁটে।"),
            "frog": ("The frog jumps beside the pond.", "ব্যাঙটি পুকুরের পাশে লাফ দেয়।"),
            "goat": ("The goat eats leaves near the village path.", "ছাগলটি গ্রামের পথের পাশে পাতা খায়।"),
        },
    },
    "fish": {
        "introductionEn": "Fish live in rivers, ponds, and seas. Fish are important in everyday life in Bangladesh.",
        "introductionBn": "মাছ নদী, পুকুর ও সাগরে বাস করে। বাংলাদেশের দৈনন্দিন জীবনে মাছ গুরুত্বপূর্ণ।",
        "completionEn": "Fish such as carp, rohu, hilsa, and prawn are familiar in Bangladesh. They live in different kinds of water.",
        "completionBn": "রুই, রোহু, ইলিশ ও চিংড়ির মতো মাছ বাংলাদেশে পরিচিত। তারা বিভিন্ন ধরনের পানিতে বাস করে।",
        "completionWords": ["FISH", "CARP", "ROHU", "HILSA", "PRAWN"],
        "lessons": {
            "fish": ("A fish swims in the pond.", "একটি মাছ পুকুরে সাঁতার কাটে।"),
            "eel": ("The eel moves like a snake in water.", "ঈল মাছটি পানিতে সাপের মতো চলে।"),
            "cod": ("Cod is a fish that lives in the sea.", "কড এক ধরনের মাছ, যা সাগরে বাস করে।"),
            "carp": ("A carp swims in fresh water.", "রুই মাছ মিঠা পানিতে সাঁতার কাটে।"),
            "rohu": ("Rohu is a popular fish in Bangladesh.", "রোহু বাংলাদেশে একটি জনপ্রিয় মাছ।"),
            "tuna": ("A tuna can swim quickly in the sea.", "টুনা মাছ সাগরে দ্রুত সাঁতার কাটতে পারে।"),
            "crab": ("The crab walks sideways near the water.", "কাঁকড়াটি পানির কাছে পাশ ফিরে হাঁটে।"),
            "hilsa": ("Hilsa is the national fish of Bangladesh.", "ইলিশ বাংলাদেশের জাতীয় মাছ।"),
            "prawn": ("We can find prawn in rivers and farms.", "নদী ও ঘেরে চিংড়ি পাওয়া যায়।"),
            "shark": ("A shark is a strong fish of the sea.", "হাঙর সাগরের একটি শক্তিশালী মাছ।"),
        },
    },
    "birds": {
        "introductionEn": "Birds have feathers and wings. Many kinds of birds live in Bangladesh.",
        "introductionBn": "পাখির পালক ও ডানা আছে। বাংলাদেশে অনেক ধরনের পাখি বাস করে।",
        "completionEn": "An owl rests at night, while a crow, myna, and robin are active by day. Birds share our trees, fields, and wetlands.",
        "completionBn": "পেঁচা রাতে বিশ্রাম নেয়, আর কাক, শালিক ও রবিন দিনে সক্রিয় থাকে। পাখিরা আমাদের গাছ, মাঠ ও জলাভূমিতে বাস করে।",
        "completionWords": ["OWL", "CROW", "MYNA", "ROBIN"],
        "lessons": {
            "owl": ("The owl can see well at night.", "পেঁচা রাতে ভালো দেখতে পারে।"),
            "crow": ("A crow calls from the mango tree.", "আমগাছ থেকে একটি কাক ডাকে।"),
            "myna": ("The myna walks across the field.", "শালিকটি মাঠের ওপর দিয়ে হাঁটে।"),
            "swan": ("The swan glides across the water.", "রাজহাঁসটি পানির ওপর দিয়ে ভেসে যায়।"),
            "wren": ("A wren is a small, lively bird.", "রেন একটি ছোট ও চঞ্চল পাখি।"),
            "crane": ("The crane stands in shallow water.", "সারসটি অগভীর পানিতে দাঁড়িয়ে থাকে।"),
            "eagle": ("The eagle flies high above the hills.", "ঈগলটি পাহাড়ের অনেক ওপরে উড়ে।"),
            "heron": ("A heron looks for fish beside the river.", "বকটি নদীর পাশে মাছ খোঁজে।"),
            "robin": ("The robin sings from a tree branch.", "রবিন পাখিটি গাছের ডাল থেকে গান গায়।"),
            "stork": ("The stork walks slowly through the wetland.", "সারসজাতীয় পাখিটি জলাভূমিতে ধীরে হাঁটে।"),
        },
    },
    "flowers": {
        "introductionEn": "Flowers grow in gardens, fields, and water. Their colors and scents brighten our surroundings.",
        "introductionBn": "ফুল বাগান, মাঠ ও পানিতে জন্মায়। ফুলের রং ও গন্ধ আমাদের চারপাশ সুন্দর করে।",
        "completionEn": "A bud opens into a flower. Rose, lotus, daisy, and tulip show how flowers can have different shapes and colors.",
        "completionBn": "কুঁড়ি ফুটে ফুল হয়। গোলাপ, পদ্ম, ডেইজি ও টিউলিপ দেখায় যে ফুলের আকার ও রং কত ভিন্ন হতে পারে।",
        "completionWords": ["BUD", "ROSE", "LOTUS", "DAISY", "TULIP"],
        "lessons": {
            "bud": ("The small bud will open soon.", "ছোট কুঁড়িটি শিগগিরই ফুটবে।"),
            "rose": ("A red rose grows in our garden.", "আমাদের বাগানে একটি লাল গোলাপ ফোটে।"),
            "aster": ("The aster has many narrow petals.", "অ্যাস্টার ফুলের অনেক সরু পাপড়ি থাকে।"),
            "daisy": ("The daisy has a bright yellow centre.", "ডেইজি ফুলের মাঝখানটি উজ্জ্বল হলুদ।"),
            "lotus": ("A lotus blooms above the pond water.", "পুকুরের পানির ওপর পদ্ম ফোটে।"),
            "pansy": ("The pansy has a colourful flower face.", "প্যানসি ফুলের মুখটি রঙিন।"),
            "petal": ("A soft petal fell from the flower.", "ফুল থেকে একটি নরম পাপড়ি ঝরে পড়ল।"),
            "thorn": ("A thorn can protect a rose plant.", "কাঁটা গোলাপগাছকে রক্ষা করতে পারে।"),
            "tulip": ("The tulip stands tall in the garden.", "টিউলিপ ফুলটি বাগানে সোজা হয়ে দাঁড়ায়।"),
            "orchid": ("An orchid can grow in a warm, damp place.", "অর্কিড উষ্ণ ও স্যাঁতসেঁতে জায়গায় জন্মাতে পারে।"),
        },
    },
    "fruits": {
        "introductionEn": "Fruits give us colour, flavour, and nourishment. Bangladesh grows many fruits in different seasons.",
        "introductionBn": "ফল আমাদের রং, স্বাদ ও পুষ্টি দেয়। বাংলাদেশে বিভিন্ন ঋতুতে নানা ফল জন্মায়।",
        "completionEn": "Mango, lemon, grape, apple, and cherry have different tastes. Washing fruit before eating keeps it clean.",
        "completionBn": "আম, লেবু, আঙুর, আপেল ও চেরির স্বাদ আলাদা। খাওয়ার আগে ফল ধুলে তা পরিষ্কার থাকে।",
        "completionWords": ["MANGO", "LEMON", "GRAPE", "APPLE", "CHERRY"],
        "lessons": {
            "fig": ("A fig is soft and sweet when ripe.", "পাকা ডুমুর নরম ও মিষ্টি হয়।"),
            "date": ("A ripe date tastes very sweet.", "পাকা খেজুর খুব মিষ্টি লাগে।"),
            "pear": ("The pear becomes soft when it is ripe.", "পাকা হলে নাশপাতি নরম হয়।"),
            "apple": ("The child shares an apple with a friend.", "শিশুটি বন্ধুর সঙ্গে একটি আপেল ভাগ করে খায়।"),
            "grape": ("Each grape grows in a bunch.", "প্রতিটি আঙুর থোকায় জন্মায়।"),
            "lemon": ("Lemon juice gives food a sour taste.", "লেবুর রস খাবারে টক স্বাদ দেয়।"),
            "mango": ("A ripe mango smells sweet in summer.", "গ্রীষ্মে পাকা আমের মিষ্টি গন্ধ ছড়ায়।"),
            "melon": ("A ripe melon is juicy and sweet.", "পাকা বাঙ্গি রসালো ও মিষ্টি হয়।"),
            "peach": ("A peach has soft skin and sweet flesh.", "পিচ ফলের নরম খোসা ও মিষ্টি শাঁস থাকে।"),
            "cherry": ("A cherry is a small fruit with a stone.", "চেরি আঁটিযুক্ত একটি ছোট ফল।"),
        },
    },
    "vegetables": {
        "introductionEn": "Vegetables are parts of plants that we cook or eat. They help make our meals healthy and colourful.",
        "introductionBn": "সবজি হলো উদ্ভিদের এমন অংশ, যা আমরা রান্না করে বা কাঁচা খাই। সবজি আমাদের খাবার স্বাস্থ্যকর ও রঙিন করে।",
        "completionEn": "Pea, okra, gourd, garlic, and carrot can all be part of a family meal. Different vegetables give our bodies different nutrients.",
        "completionBn": "মটর, ঢেঁড়স, লাউ, রসুন ও গাজর পারিবারিক খাবারের অংশ হতে পারে। বিভিন্ন সবজি আমাদের শরীরে বিভিন্ন পুষ্টি দেয়।",
        "completionWords": ["PEA", "OKRA", "GOURD", "GARLIC", "CARROT"],
        "lessons": {
            "pea": ("A green pea grows inside a pod.", "সবুজ মটরশুঁটি একটি খোসার ভেতর জন্মায়।"),
            "yam": ("A yam grows under the soil.", "মেটে আলু মাটির নিচে জন্মায়।"),
            "okra": ("Okra is a familiar green vegetable in Bangladesh.", "ঢেঁড়স বাংলাদেশে পরিচিত একটি সবুজ সবজি।"),
            "gourd": ("A bottle gourd hangs from the vine.", "লাউটি লতা থেকে ঝুলে থাকে।"),
            "carrot": ("A carrot has a crisp orange root.", "গাজরের মচমচে কমলা রঙের মূল থাকে।"),
            "garlic": ("Garlic adds a strong smell to curry.", "রসুন তরকারিতে তীব্র সুগন্ধ যোগ করে।"),
            "ginger": ("We add ginger to tea and curry.", "আমরা চা ও তরকারিতে আদা দিই।"),
            "potato": ("The potato cooks with many vegetables.", "আলু অনেক সবজির সঙ্গে রান্না হয়।"),
            "radish": ("Fresh radish grows well in winter.", "শীতকালে তাজা মূলা ভালো জন্মায়।"),
            "turnip": ("The turnip has a round root underground.", "শালগমের গোল মূল মাটির নিচে থাকে।"),
        },
    },
    "trees_plants": {
        "introductionEn": "Trees and plants give us shade, food, fibres, and fresh air. Green plants grow all across Bangladesh.",
        "introductionBn": "গাছ ও উদ্ভিদ আমাদের ছায়া, খাবার, আঁশ ও নির্মল বাতাস দেয়। সারা বাংলাদেশে সবুজ উদ্ভিদ জন্মায়।",
        "completionEn": "A tree has roots, leaves, and a trunk. Palm, neem, teak, and bamboo are useful plants found in Bangladesh.",
        "completionBn": "একটি গাছের শিকড়, পাতা ও কাণ্ড থাকে। তাল, নিম, সেগুন ও বাঁশ বাংলাদেশে পাওয়া উপকারী উদ্ভিদ।",
        "completionWords": ["TREE", "ROOT", "PALM", "NEEM", "TEAK"],
        "lessons": {
            "tree": ("The tree gives shade beside the road.", "গাছটি রাস্তার পাশে ছায়া দেয়।"),
            "herb": ("A useful herb grows beside the tree.", "গাছের পাশে একটি উপকারী ভেষজ উদ্ভিদ জন্মায়।"),
            "root": ("The root holds the plant in the soil.", "শিকড় উদ্ভিদকে মাটিতে ধরে রাখে।"),
            "palm": ("A tall palm tree grows near the pond.", "পুকুরের পাশে একটি লম্বা তালগাছ জন্মায়।"),
            "neem": ("The neem tree has bitter leaves.", "নিমগাছের পাতা তিতা।"),
            "teak": ("Teak is a tall tree with strong wood.", "সেগুন শক্ত কাঠের একটি লম্বা গাছ।"),
            "fern": ("A fern grows well in a shady place.", "ফার্ন ছায়াযুক্ত জায়গায় ভালো জন্মায়।"),
            "bush": ("A small bird hides inside the bush.", "একটি ছোট পাখি ঝোপের ভেতর লুকায়।"),
            "grass": ("Green grass covers the school field.", "সবুজ ঘাস স্কুলের মাঠ ঢেকে রাখে।"),
            "trunk": ("The trunk supports the branches of a tree.", "গাছের কাণ্ড ডালগুলোকে ধরে রাখে।"),
        },
    },
    "body_parts": {
        "introductionEn": "Our body has many parts that help us move, sense, work, and play.",
        "introductionBn": "আমাদের শরীরের অনেক অংশ আছে, যা নড়াচড়া, অনুভব, কাজ ও খেলায় সাহায্য করে।",
        "completionEn": "We see with each eye, hear with each ear, and use a hand and arm to work. Caring for every body part keeps us healthy.",
        "completionBn": "আমরা চোখ দিয়ে দেখি, কান দিয়ে শুনি এবং হাত ও বাহু দিয়ে কাজ করি। শরীরের প্রতিটি অংশের যত্ন নিলে আমরা সুস্থ থাকি।",
        "completionWords": ["EYE", "EAR", "HAND", "ARM"],
        "lessons": {
            "arm": ("Raise your arm before you throw the ball.", "বল ছোড়ার আগে তোমার বাহু ওপরে তোলো।"),
            "ear": ("Each ear helps us hear sound.", "প্রতিটি কান আমাদের শব্দ শুনতে সাহায্য করে।"),
            "eye": ("The eye helps us see colour and light.", "চোখ আমাদের রং ও আলো দেখতে সাহায্য করে।"),
            "leg": ("Each leg helps us stand and walk.", "প্রতিটি পা আমাদের দাঁড়াতে ও হাঁটতে সাহায্য করে।"),
            "lip": ("Your lip helps you speak and smile.", "ঠোঁট তোমাকে কথা বলতে ও হাসতে সাহায্য করে।"),
            "back": ("Keep your back straight while sitting.", "বসে থাকার সময় পিঠ সোজা রাখো।"),
            "chin": ("The chin is below the mouth.", "থুতনি মুখের নিচে থাকে।"),
            "hair": ("Clean hair feels soft and healthy.", "পরিষ্কার চুল নরম ও স্বাস্থ্যকর থাকে।"),
            "hand": ("Wash each hand before eating.", "খাওয়ার আগে প্রতিটি হাত ধুয়ে নাও।"),
            "nose": ("The nose helps us smell a flower.", "নাক আমাদের ফুলের গন্ধ পেতে সাহায্য করে।"),
        },
    },
    "colors": {
        "introductionEn": "Colours help us describe the things we see. Bangladesh is full of colours in nature, clothes, and art.",
        "introductionBn": "রং আমাদের দেখা জিনিস বর্ণনা করতে সাহায্য করে। প্রকৃতি, পোশাক ও শিল্পে বাংলাদেশ নানা রঙে ভরা।",
        "completionEn": "The Bangladesh flag has a red circle. White clouds, black crows, golden paddy, and orange sunsets add colour to our surroundings.",
        "completionBn": "বাংলাদেশের পতাকায় একটি লাল বৃত্ত আছে। সাদা মেঘ, কালো কাক, সোনালি ধান ও কমলা সূর্যাস্ত আমাদের চারপাশে রং যোগ করে।",
        "completionWords": ["RED", "WHITE", "BLACK", "GOLD", "ORANGE"],
        "lessons": {
            "red": ("The circle on our national flag is red.", "আমাদের জাতীয় পতাকার বৃত্তটি লাল।"),
            "gold": ("Ripe paddy looks gold in the field.", "মাঠে পাকা ধান সোনালি দেখায়।"),
            "pink": ("The pink flower opens in the morning.", "গোলাপি ফুলটি সকালে ফোটে।"),
            "black": ("A crow has shiny black feathers.", "কাকের চকচকে কালো পালক থাকে।"),
            "brown": ("The wet soil looks dark brown.", "ভেজা মাটি গাঢ় বাদামি দেখায়।"),
            "white": ("A white cloud floats in the sky.", "একটি সাদা মেঘ আকাশে ভাসে।"),
            "bright": ("The bright sun lights the school yard.", "উজ্জ্বল সূর্য স্কুলের উঠান আলোকিত করে।"),
            "orange": ("The evening sky turns orange.", "সন্ধ্যার আকাশ কমলা রং ধারণ করে।"),
            "purple": ("The purple cloth has a simple pattern.", "বেগুনি কাপড়ে একটি সহজ নকশা আছে।"),
            "silver": ("Hilsa has bright silver scales.", "ইলিশের উজ্জ্বল রুপালি আঁশ আছে।"),
        },
    },
    "family": {
        "introductionEn": "A family is a group of people who care for one another. Families can be large or small.",
        "introductionBn": "পরিবার হলো এমন একদল মানুষ, যারা একে অন্যের যত্ন নেয়। পরিবার বড় বা ছোট হতে পারে।",
        "completionEn": "A child may live with a sister, brother, son, or elder. Every caring family member deserves kindness and respect.",
        "completionBn": "একটি শিশু বোন, ভাই, ছেলে বা বয়োজ্যেষ্ঠের সঙ্গে থাকতে পারে। পরিবারের প্রতিটি যত্নশীল সদস্য ভালোবাসা ও সম্মান পাওয়ার যোগ্য।",
        "completionWords": ["CHILD", "SISTER", "BROTHER", "SON", "ELDER"],
        "lessons": {
            "son": ("The son helps his family at home.", "ছেলেটি বাড়িতে তার পরিবারকে সাহায্য করে।"),
            "aunt": ("My aunt tells us a funny story.", "আমার খালা আমাদের একটি মজার গল্প বলেন।"),
            "girl": ("The girl reads with her family.", "মেয়েটি তার পরিবারের সঙ্গে পড়ে।"),
            "child": ("Every child needs care and time to play.", "প্রতিটি শিশুর যত্ন ও খেলার সময় দরকার।"),
            "elder": ("We listen politely when an elder speaks.", "বয়োজ্যেষ্ঠ কেউ কথা বললে আমরা ভদ্রভাবে শুনি।"),
            "twins": ("The twins share their picture book.", "যমজ শিশুরা তাদের ছবির বই ভাগ করে দেখে।"),
            "family": ("Our family eats dinner together.", "আমাদের পরিবার একসঙ্গে রাতের খাবার খায়।"),
            "friend": ("A good friend listens and shares.", "ভালো বন্ধু কথা শোনে এবং ভাগ করে নেয়।"),
            "sister": ("My sister waters the garden plants.", "আমার বোন বাগানের গাছে পানি দেয়।"),
            "brother": ("My brother walks with me to school.", "আমার ভাই আমার সঙ্গে স্কুলে হাঁটে।"),
        },
    },
    "school": {
        "introductionEn": "School is a place to learn, ask questions, and grow with friends and teachers.",
        "introductionBn": "স্কুল হলো শেখা, প্রশ্ন করা এবং বন্ধু ও শিক্ষকদের সঙ্গে বেড়ে ওঠার জায়গা।",
        "completionEn": "A pen, paper, map, board, and chair help us learn at school. We care for shared classroom things.",
        "completionBn": "কলম, কাগজ, মানচিত্র, বোর্ড ও চেয়ার স্কুলে আমাদের শিখতে সাহায্য করে। আমরা শ্রেণিকক্ষের সবার ব্যবহার করা জিনিসের যত্ন নিই।",
        "completionWords": ["PEN", "PAPER", "MAP", "BOARD", "CHAIR"],
        "lessons": {
            "bag": ("I carry my books in a school bag.", "আমি স্কুলের ব্যাগে আমার বই বহন করি।"),
            "map": ("The map shows the rivers of Bangladesh.", "মানচিত্রে বাংলাদেশের নদীগুলো দেখা যায়।"),
            "pen": ("I use a pen to write my name.", "আমি কলম দিয়ে আমার নাম লিখি।"),
            "test": ("A test helps the teacher see what we learned.", "পরীক্ষা শিক্ষককে আমাদের শেখা বুঝতে সাহায্য করে।"),
            "board": ("The teacher writes a word on the board.", "শিক্ষক বোর্ডে একটি শব্দ লেখেন।"),
            "chair": ("I sit safely on the classroom chair.", "আমি শ্রেণিকক্ষের চেয়ারে নিরাপদভাবে বসি।"),
            "globe": ("The globe shows land and water on Earth.", "গ্লোব পৃথিবীর স্থল ও পানি দেখায়।"),
            "paper": ("We draw a village scene on paper.", "আমরা কাগজে গ্রামের একটি দৃশ্য আঁকি।"),
            "eraser": ("The eraser removes a pencil mark.", "রাবার পেনসিলের দাগ মুছে দেয়।"),
            "pencil": ("Sharpen the pencil carefully before writing.", "লেখার আগে সাবধানে পেনসিলটি ছেঁটে নাও।"),
        },
    },
    "transport": {
        "introductionEn": "Transport helps people and goods move from one place to another. Roads and rivers are both important in Bangladesh.",
        "introductionBn": "যানবাহন মানুষ ও পণ্যকে এক জায়গা থেকে অন্য জায়গায় নিয়ে যায়। বাংলাদেশে সড়ক ও নদী দুটিই গুরুত্বপূর্ণ।",
        "completionEn": "A bus, car, van, and truck travel on roads. A boat, ship, and canoe travel on water, while a plane flies in the sky.",
        "completionBn": "বাস, গাড়ি, ভ্যান ও ট্রাক সড়কে চলে। নৌকা, জাহাজ ও ডিঙি পানিতে চলে, আর বিমান আকাশে ওড়ে।",
        "completionWords": ["BUS", "CAR", "VAN", "TRUCK", "BOAT", "SHIP", "CANOE", "PLANE"],
        "lessons": {
            "bus": ("The school bus stops beside the gate.", "স্কুলবাসটি ফটকের পাশে থামে।"),
            "car": ("The car waits at the traffic light.", "গাড়িটি ট্রাফিক বাতিতে অপেক্ষা করে।"),
            "van": ("The van carries boxes to the market.", "ভ্যানটি বাজারে বাক্স নিয়ে যায়।"),
            "boat": ("A boat crosses the wide river.", "একটি নৌকা প্রশস্ত নদী পার হয়।"),
            "cart": ("The cart carries vegetables to the village market.", "গাড়িটি গ্রামের বাজারে সবজি নিয়ে যায়।"),
            "ship": ("The ship carries goods across the sea.", "জাহাজটি সাগর পেরিয়ে পণ্য বহন করে।"),
            "canoe": ("The small canoe moves with a paddle.", "ছোট ডিঙি বৈঠার সাহায্যে চলে।"),
            "train": ("The train travels between busy stations.", "ট্রেনটি ব্যস্ত স্টেশনগুলোর মধ্যে চলাচল করে।"),
            "plane": ("The plane flies above the clouds.", "বিমানটি মেঘের ওপর দিয়ে ওড়ে।"),
            "truck": ("The truck carries heavy goods on the highway.", "ট্রাকটি মহাসড়কে ভারী পণ্য বহন করে।"),
        },
    },
    "weather": {
        "introductionEn": "Weather tells us what the air and sky are like today. Bangladesh has sunshine, rain, wind, fog, and seasonal storms.",
        "introductionBn": "আবহাওয়া আমাদের আজকের বাতাস ও আকাশের অবস্থা জানায়। বাংলাদেশে রোদ, বৃষ্টি, বাতাস, কুয়াশা ও মৌসুমি ঝড় হয়।",
        "completionEn": "A day can feel hot and dry. Rain and wind may make it wet and cold, while fog can hide the road.",
        "completionBn": "একটি দিন গরম ও শুকনো লাগতে পারে। বৃষ্টি ও বাতাস চারপাশ ভেজা ও ঠান্ডা করতে পারে, আর কুয়াশা রাস্তা ঢেকে দিতে পারে।",
        "completionWords": ["HOT", "DRY", "RAIN", "WIND", "WET", "COLD", "FOG"],
        "lessons": {
            "dry": ("The school field becomes dry after sunshine.", "রোদ ওঠার পর স্কুলের মাঠ শুকিয়ে যায়।"),
            "fog": ("Morning fog makes the distant trees hard to see.", "সকালের কুয়াশায় দূরের গাছ দেখা কঠিন হয়।"),
            "hot": ("The afternoon feels hot before the rain.", "বৃষ্টির আগে বিকেলটি গরম লাগে।"),
            "wet": ("The road is wet after monsoon rain.", "বর্ষার বৃষ্টির পর রাস্তা ভেজা থাকে।"),
            "cold": ("A cold morning needs a warm sweater.", "ঠান্ডা সকালে গরম সোয়েটার দরকার হয়।"),
            "rain": ("Heavy rain fills the village pond.", "ভারী বৃষ্টিতে গ্রামের পুকুর ভরে যায়।"),
            "snow": ("Snow falls in very cold places, not usually in Bangladesh.", "খুব ঠান্ডা জায়গায় তুষার পড়ে, বাংলাদেশে সাধারণত পড়ে না।"),
            "star": ("A bright star appears in the clear night sky.", "পরিষ্কার রাতের আকাশে একটি উজ্জ্বল তারা দেখা যায়।"),
            "wind": ("Strong wind moves the coconut leaves.", "জোর বাতাস নারকেলগাছের পাতা নাড়ায়।"),
            "storm": ("We stay indoors and safe during a storm.", "ঝড়ের সময় আমরা ঘরের ভেতর নিরাপদে থাকি।"),
        },
    },
    "food_kitchen": {
        "introductionEn": "Food gives us energy, and the kitchen is where many family meals are prepared.",
        "introductionBn": "খাবার আমাদের শক্তি দেয়, আর রান্নাঘরে পরিবারের অনেক খাবার তৈরি হয়।",
        "completionEn": "Dal, egg, meat, and bread can make a nourishing meal. A bowl, pot, and pan help us prepare and serve food safely.",
        "completionBn": "ডাল, ডিম, মাংস ও রুটি দিয়ে পুষ্টিকর খাবার তৈরি হয়। বাটি, হাঁড়ি ও কড়াই নিরাপদে খাবার তৈরি ও পরিবেশনে সাহায্য করে।",
        "completionWords": ["DAL", "EGG", "MEAT", "BREAD", "BOWL", "POT", "PAN"],
        "lessons": {
            "dal": ("We often eat dal with rice.", "আমরা প্রায়ই ভাতের সঙ্গে ডাল খাই।"),
            "egg": ("A boiled egg can be part of breakfast.", "সেদ্ধ ডিম সকালের নাশতার অংশ হতে পারে।"),
            "pot": ("The rice cooks inside the pot.", "হাঁড়ির ভেতর ভাত রান্না হয়।"),
            "pan": ("An adult heats the pan on the stove.", "একজন বড় মানুষ চুলায় কড়াই গরম করেন।"),
            "tea": ("Adults may enjoy warm tea in the morning.", "বড়রা সকালে গরম চা পান করতে পারেন।"),
            "bowl": ("We serve warm soup in a bowl.", "আমরা বাটিতে গরম স্যুপ পরিবেশন করি।"),
            "meat": ("Cook meat well before eating it.", "মাংস খাওয়ার আগে ভালোভাবে রান্না করো।"),
            "salt": ("A small amount of salt adds flavour.", "সামান্য লবণ খাবারে স্বাদ যোগ করে।"),
            "bread": ("Fresh bread can be part of breakfast.", "তাজা রুটি সকালের নাশতার অংশ হতে পারে।"),
            "honey": ("A spoon of honey tastes sweet.", "এক চামচ মধু মিষ্টি লাগে।"),
        },
    },
    "clothing": {
        "introductionEn": "Clothing covers and protects our bodies. We choose clothes for the weather, work, school, and celebrations.",
        "introductionBn": "পোশাক আমাদের শরীর ঢাকে ও রক্ষা করে। আবহাওয়া, কাজ, স্কুল ও উৎসব অনুযায়ী আমরা পোশাক বেছে নিই।",
        "completionEn": "A hat or cap covers the head, while a shoe protects the foot. A shirt, coat, cloth, or scarf can suit different weather and occasions.",
        "completionBn": "টুপি মাথা ঢাকে, আর জুতা পা রক্ষা করে। শার্ট, কোট, কাপড় বা ওড়না বিভিন্ন আবহাওয়া ও অনুষ্ঠানে মানায়।",
        "completionWords": ["HAT", "CAP", "SHOE", "SHIRT", "COAT", "CLOTH", "SCARF"],
        "lessons": {
            "hat": ("The farmer wears a hat in the sun.", "কৃষক রোদে একটি টুপি পরেন।"),
            "cap": ("My school cap shades my eyes.", "আমার স্কুলের ক্যাপ চোখে ছায়া দেয়।"),
            "shoe": ("Tie each shoe before you walk.", "হাঁটার আগে প্রতিটি জুতার ফিতা বাঁধো।"),
            "belt": ("The belt keeps the trousers in place.", "বেল্ট প্যান্ট ঠিক জায়গায় ধরে রাখে।"),
            "coat": ("A warm coat protects us on a cold day.", "গরম কোট ঠান্ডার দিনে আমাদের রক্ষা করে।"),
            "vest": ("The child wears a soft vest under a shirt.", "শিশুটি শার্টের নিচে নরম গেঞ্জি পরে।"),
            "cloth": ("We can make clothes from soft cloth.", "নরম কাপড় দিয়ে আমরা পোশাক তৈরি করতে পারি।"),
            "pants": ("The child wears clean pants to school.", "শিশুটি স্কুলে পরিষ্কার প্যান্ট পরে।"),
            "shirt": ("The student wears a clean school shirt.", "শিক্ষার্থী পরিষ্কার স্কুল শার্ট পরে।"),
            "scarf": ("The scarf covers the neck in cool weather.", "ঠান্ডা আবহাওয়ায় স্কার্ফ গলা ঢেকে রাখে।"),
        },
    },
    "numbers": {
        "introductionEn": "Numbers help us count, compare, measure, and share things fairly.",
        "introductionBn": "সংখ্যা আমাদের গোনা, তুলনা, মাপা ও ন্যায্যভাবে ভাগ করতে সাহায্য করে।",
        "completionEn": "We can count from one to ten, compare many objects, and arrange things as a pair. Numbers are useful every day.",
        "completionBn": "আমরা এক থেকে দশ পর্যন্ত গুনতে, অনেক বস্তু তুলনা করতে এবং জিনিস জোড়ায় সাজাতে পারি। সংখ্যা প্রতিদিন কাজে লাগে।",
        "completionWords": ["ONE", "TWO", "TEN", "MANY", "PAIR"],
        "lessons": {
            "one": ("One sun shines in the daytime sky.", "দিনের আকাশে একটি সূর্য আলো দেয়।"),
            "two": ("Two birds sit on the branch.", "দুটি পাখি ডালে বসে আছে।"),
            "ten": ("Ten fingers help us count.", "দশটি আঙুল আমাদের গুনতে সাহায্য করে।"),
            "four": ("Four legs support the table.", "চারটি পা টেবিলটি ধরে রাখে।"),
            "many": ("Many boats travel on the river.", "নদীতে অনেক নৌকা চলাচল করে।"),
            "pair": ("A pair of shoes has two shoes.", "এক জোড়া জুতায় দুটি জুতা থাকে।"),
            "zero": ("Zero means there is nothing to count.", "শূন্য মানে গোনার মতো কিছু নেই।"),
            "dozen": ("A dozen eggs means twelve eggs.", "এক ডজন ডিম মানে বারোটি ডিম।"),
            "eight": ("Eight children stand in a line.", "আটজন শিশু এক সারিতে দাঁড়ায়।"),
            "three": ("Three mangoes are in the basket.", "ঝুড়িতে তিনটি আম আছে।"),
        },
    },
}
